apiVersion: batch/v1
kind: CronJob
metadata:
  name: ecr-secret-refresh
  namespace: composio
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - |
              # Install kubectl
              curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
              chmod +x kubectl
              mv kubectl /usr/local/bin/

              # Get ECR token and update secret
              PASSWORD=$(aws ecr get-login-password --region us-east-1)
              kubectl create secret docker-registry ecr-secret \
                --docker-server=008971668139.dkr.ecr.us-east-1.amazonaws.com \
                --docker-username=AWS \
                --docker-password="$PASSWORD" \
                --namespace=composio-poc \
                --dry-run=client -o yaml | \
                kubectl replace -f -
            env:
            - name: AWS_DEFAULT_REGION
              value: us-east-1
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: AWS_ACCESS_KEY_ID
                  name: aws-credentials
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: AWS_SECRET_ACCESS_KEY
                  name: aws-credentials
            image: amazon/aws-cli:2.15.30
            imagePullPolicy: IfNotPresent
            name: ecr-refresh
            resources:
              limits:
                ephemeral-storage: 1Gi
              requests:
                cpu: 500m
                ephemeral-storage: 1Gi
                memory: 2Gi
            securityContext:
              capabilities:
                drop:
                - NET_RAW
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext:
            seccompProfile:
              type: RuntimeDefault
          serviceAccount: ecr-secret-refresher
          serviceAccountName: ecr-secret-refresher
          terminationGracePeriodSeconds: 30
          tolerations:
          - effect: NoSchedule
            key: kubernetes.io/arch
            operator: Equal
            value: amd64
  schedule: 0 */6 * * *
  successfulJobsHistoryLimit: 3
  suspend: false