{{- if and .Values.frontend.serviceAccount.enabled .Values.frontend.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.frontend.serviceAccount.name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    {{- with .Values.frontend.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- with .Values.frontend.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
