apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-apollo
  labels:
    app: apollo
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.apollo.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: apollo
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: apollo
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: apollo
          image: "{{ .Values.apollo.image.repository }}:{{ .Values.apollo.image.tag }}"
          imagePullPolicy: {{ .Values.apollo.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - containerPort: 9900
          livenessProbe:
            httpGet:
              path: /api/healthz
              port: 9900
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/healthz
              port: 9900
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          env:
            - name: PORT
              value: "9900"
            - name: HOSTNAME
              value: "0.0.0.0"
            - name: NODE_ENV
              value: "production"
            - name: AWS_REGION
              value: {{ .Values.aws.region | quote }}
            - name: COMPOSIO_ENV
              value: "production"
            - name: USE_CLICKHOUSE_FOR_LOGS
              value: "false"
            - name: SELF_HOSTED
              value: "true"
            - name: NODE_OPTIONS
              value: "--max-old-space-size=4096"
            - name: THERMOS_URL
              value: {{ printf "http://%s-thermos:8180" .Release.Name | quote }}
 
            - name: OVERWRITE_APOLLO_URL
              value: {{ .Values.apollo.overwrite_apollo_url | default (printf "http://%s-apollo:9900" .Release.Name) | quote }}
            - name: OAUTH2_REDIRECT_URI_OVERRIDE
              value: {{ .Values.apollo.oauth2_redirect_uri_override | default (printf "http://%s-apollo:9900/api/v3/toolkits/auth/callback" .Release.Name) | quote }}
            - name: MERCURY_URL
              value: "https://mercury.composio.dev"
            - name: SERVICE_NAME
              value: "apollo"
            - name: APOLLO_URL
              value: {{ .Values.apollo.apollo_url | default (printf "http://%s-apollo:9900" .Release.Name) | quote }}
            - name: MAX_AUTH_FAILURES_FOR_EXPIRY
              value: "1"
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: external-redis-secret
                  key: url      
            - name: ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-encryption-key
                  key: ENCRYPTION_KEY
            - name: COMPOSIO_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-composio-api-key
                  key: COMPOSIO_API_KEY
            - name: APOLLO_ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-apollo-admin-token
                  key: APOLLO_ADMIN_TOKEN
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: external-postgres-secret
                  key: url
            - name: ORG_API_KEY_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-encryption-key
                  key: ENCRYPTION_KEY
            # OpenTelemetry configuration
            {{- if .Values.otel.enabled }}
            - name: OTEL_ENABLED
              value: {{ .Values.otel.enabled | quote }}
            - name: OTEL_SERVICE_NAME
              value: {{ .Values.otel.apollo.serviceName | default "apollo" | quote }}
            - name: OTEL_SERVICE_VERSION
              value: {{ .Values.otel.apollo.serviceVersion | default "1.0.0" | quote }}
            - name: OTEL_ENVIRONMENT
              value: {{ .Values.otel.environment | default .Values.global.environment | default "development" | quote }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.otel.exporter.otlp.endpoint | default (printf "http://%s-otel-collector:4317" .Release.Name) | quote }}
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: {{ .Values.otel.exporter.otlp.endpoint | default (printf "http://%s-otel-collector:4317" .Release.Name) | quote }}
            - name: OTEL_EXPORTER_OTLP_INSECURE
              value: {{ .Values.otel.exporter.otlp.insecure | default "true" | quote }}
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_METRICS_EXPORTER
              value: "otlp"
            - name: OTEL_LOGS_EXPORTER
              value: "otlp"
            # Custom Apollo variables for backward compatibility
            - name: ENABLE_OTEL_METRICS
              value: {{ .Values.otel.metrics.enabled | default "true" | quote }}
            - name: OTEL_METRICS_ENDPOINT
              value: {{ .Values.otel.apollo.metricsEndpoint | default (printf "http://%s-otel-collector:4318/v1/metrics" .Release.Name) | quote }}
            # OTEL Resource attributes
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name={{ .Values.otel.apollo.serviceName | default "apollo" }},service.version={{ .Values.otel.apollo.serviceVersion | default "1.0.0" }},deployment.environment={{ .Values.otel.environment | default .Values.global.environment | default "development" }}"
            {{- end }}
            {{- if .Values.apollo.env }}
            {{- toYaml .Values.apollo.env | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.apollo.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-apollo
  labels:
    app: apollo
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.apollo.service.type }}
  ports:
    - port: {{ .Values.apollo.service.port }}
      targetPort: 9900
      protocol: TCP
      {{- if and (eq .Values.apollo.service.type "NodePort") .Values.apollo.service.nodePort }}
      nodePort: {{ .Values.apollo.service.nodePort }}
      {{- end }}
  selector:
    app: apollo
    release: {{ .Release.Name }}
---
{{- if .Values.apollo.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-apollo
  labels:
    app: apollo
    release: {{ .Release.Name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-apollo
  minReplicas: {{ .Values.apollo.autoscaling.minReplicas | default 2 }}
  maxReplicas: {{ .Values.apollo.autoscaling.maxReplicas | default 10 }}
  metrics:
    {{- if .Values.apollo.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.apollo.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.apollo.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.apollo.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.apollo.autoscaling.scaleDownStabilizationWindowSeconds | default 300 }}
      policies:
      - type: Percent
        value: {{ .Values.apollo.autoscaling.scaleDownPercent | default 10 }}
        periodSeconds: {{ .Values.apollo.autoscaling.scaleDownPeriodSeconds | default 60 }}
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.apollo.autoscaling.scaleUpStabilizationWindowSeconds | default 60 }}
      policies:
      - type: Percent
        value: {{ .Values.apollo.autoscaling.scaleUpPercent | default 100 }}
        periodSeconds: {{ .Values.apollo.autoscaling.scaleUpPeriodSeconds | default 15 }}
      - type: Pods
        value: {{ .Values.apollo.autoscaling.scaleUpPods | default 4 }}
        periodSeconds: {{ .Values.apollo.autoscaling.scaleUpPeriodSeconds | default 15 }}
      selectPolicy: Max
{{- end }}
