{{- if .Values.database.createDb }}
{{- $rootDb := $.Values.database -}}
{{- $apolloDb := $rootDb.apollo | default dict -}}
{{- $thermosDb := $rootDb.thermos | default dict -}}
{{- $dbs := list
  (dict "name" ($apolloDb.database | default "") "host" (default $rootDb.host $apolloDb.host) "port" (default $rootDb.port $apolloDb.port) "user" (default $rootDb.user $apolloDb.user) "sslmode" (default $rootDb.sslmode $apolloDb.sslmode) "secret" "external-postgres-secret")
  (dict "name" ($thermosDb.database | default "") "host" (default $rootDb.host $thermosDb.host) "port" (default $rootDb.port $thermosDb.port) "user" (default $rootDb.user $thermosDb.user) "sslmode" (default $rootDb.sslmode $thermosDb.sslmode) "secret" "external-thermos-postgres-secret")
}}
{{- range $index, $db := $dbs }}
{{- if and $db.name $db.host $db.user }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-createdb-%s" $.Release.Name (printf "%s-%d" ($db.name | lower | replace "_" "-") $index) | trunc 63 }}
  labels:
    app: create-db
    release: {{ $.Release.Name }}
  annotations:
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        app: create-db
        release: {{ $.Release.Name }}
    spec:
      {{- if $.Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml $.Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      restartPolicy: OnFailure
      containers:
        - name: createdb-{{ $index }}
          image: "postgres:16-alpine"
          imagePullPolicy: IfNotPresent
          env:
            - name: DBNAME
              value: {{ $db.name | quote }}
            - name: ACCESS_SVC_CONNSTR
              value: host={{ $db.host }} user={{ $db.user }} port={{ default "5432" $db.port }} sslmode={{ default "require" $db.sslmode }} connect_timeout=3
            - name: SQLCOMMAND
              value: |
                SELECT format('CREATE DATABASE %I', :'dbname')
                WHERE NOT EXISTS (
                   SELECT
                     FROM pg_database
                    WHERE datname=:'dbname'
                )
                \gexec
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $db.secret }}
                  key: password
          command:
            - sh
            - -c
            - >
                while ! pg_isready -U {{ $db.user }} -h {{ $db.host }} -p {{ default "5432" $db.port }}; do sleep 1; done;
                echo "${SQLCOMMAND}" | psql --file=- --echo-queries -d "${ACCESS_SVC_CONNSTR}" \
                  --set ON_ERROR_STOP=1 \
                  --set dbname="${DBNAME}"
  backoffLimit: 2
{{- end }}
{{- end }}
{{- end }}

