apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-db-init
  labels:
    app: db-init
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-9"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded

spec:
  backoffLimit: 3
  activeDeadlineSeconds: 600
  template:
    metadata:
      labels:
        app: db-init
        release: {{ .Release.Name }}
    spec:
      restartPolicy: Never
      securityContext:
        #runAsNonRoot: true
        #runAsUser: 1000
        fsGroup: 2000
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: db-init
          image: "{{ .Values.dbInit.image.repository }}:{{ .Values.dbInit.image.tag }}"
          imagePullPolicy: {{ .Values.dbInit.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            seccompProfile:
              type: RuntimeDefault
          command: ["/bin/sh"]
          args:
            - -c
            - |
              echo "🚀 Starting database initialization..."
              echo "📊 Database URL: ${DATABASE_URL%/*}/***"
              
              # Test database connectivity
              echo "🔍 Testing database connectivity..."
              if ! timeout 30 sh -c 'until pg_isready -d "$DATABASE_URL"; do sleep 1; done'; then
                echo "❌ Database connection failed after 30 seconds"
                echo "🔍 Checking database URL format..."
                echo "Database URL pattern: ${DATABASE_URL%@*}@***"
                exit 1
              fi
              
              echo "✅ Database connection successful"
              
              # Run the actual initialization
              echo "🔧 Running database initialization..."
              exec /usr/local/bin/composio-init
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: external-postgres-secret
                  key: url
            - name: COMPOSIO_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: COMPOSIO_API_KEY
            - name: BOOTSTRAP_API_KEY_VALUE
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: BOOTSTRAP_API_KEY_VALUE
            - name: ADMIN_EMAIL
              value: {{ .Values.dbInit.adminEmail | default "hello@composio.dev" | quote }}
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi 
