{{- if .Values.externalSecrets.ecr.token }}
apiVersion: v1
kind: Secret
metadata:
  name: ecr-secret
  namespace: {{ include "composio.namespace" . }}
  labels:
    {{- include "composio.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf `{"auths":{"%s":{"username":"%s","password":"%s","auth":"%s"}}}` .Values.externalSecrets.ecr.server .Values.externalSecrets.ecr.username .Values.externalSecrets.ecr.token (printf "%s:%s" .Values.externalSecrets.ecr.username .Values.externalSecrets.ecr.token | b64enc) | b64enc }}
{{- end }} 