apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mcp
  labels:
    app: mcp
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.mcp.replicaCount }}
  selector:
    matchLabels:
      app: mcp
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: mcp
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: mcp
          image: "{{ .Values.mcp.image.repository }}:{{ .Values.mcp.image.tag }}"
          imagePullPolicy: {{ .Values.mcp.image.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: HOSTNAME
              value: "0.0.0.0"
            - name: COMPOSIO_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-composio-api-key
                  key: COMPOSIO_API_KEY
            - name: APOLLO_COMPOSIO_BASE_URL
              value: {{ printf "http://%s-apollo:9900" .Release.Name | quote }}
            - name: APOLLO_SPEC_PATH
              value: {{ printf "http://%s-apollo:9900/api/v3/mcp-experimental-openapi.json" .Release.Name | quote }}
            - name: COMPOSIO_BASE_URL
              value: {{ printf "http://%s-apollo:9900" .Release.Name | quote }}
            - name: SELF_HOSTED
              value: "true"
            - name: MCP_BASE_URL
              value: {{ printf "http://%s-mcp:3000" .Release.Name | quote }}
            - name: SERVICE_NAME
              value: "mcp-server-next"
            - name: NEXT_PUBLIC_COMPOSIO_BASE_URL
              value: {{ printf "http://%s-apollo:9900" .Release.Name | quote }}
            - name: APOLLO_URL
              value: {{ printf "http://%s-apollo:9900" .Release.Name | quote }}
            - name: NODE_OPTIONS
              value: "--max-old-space-size=8192"
            - name: APOLLO_ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-apollo-admin-token
                  key: APOLLO_ADMIN_TOKEN
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: external-redis-secret
                  key: url
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: external-postgres-secret
                  key: url
            {{- if .Values.mcp.env }}
            {{- toYaml .Values.mcp.env | nindent 12 }}
            {{- end }}
          resources:
            requests:
              cpu: "1"
              memory: "5Gi"
            limits:
              cpu: "1"
              memory: "6Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mcp
  labels:
    app: mcp
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.mcp.service.type }}
  ports:
    - port: {{ .Values.mcp.service.port }}
      targetPort: 3000
      protocol: TCP
  selector:
    app: mcp
    release: {{ .Release.Name }} 
