{{- if and .Values.mercury.enabled (not .Values.mercury.useKnative) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "composio.fullname" . }}-mercury
  namespace: {{ include "composio.namespace" . }}
  labels:
    {{- include "composio.labels" . | nindent 4 }}
    app.kubernetes.io/component: mercury
spec:
  replicas: {{ .Values.mercury.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "composio.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mercury
  template:
    metadata:
      labels:
        {{- include "composio.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mercury
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      {{- if or .Values.nodeSelector .Values.mercury.nodeSelector }}
      nodeSelector:
        {{- with .Values.mercury.nodeSelector }}
          {{- toYaml . | nindent 8 }}
        {{- else }}
          {{- toYaml .Values.nodeSelector | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      containers:
        - name: mercury
          image: "{{ .Values.mercury.image.imageName }}"
          imagePullPolicy: {{ .Values.mercury.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.mercury.service.port | default 8080 }}
          securityContext:
            {{- toYaml .Values.mercury.securityContext | nindent 12 }}
          env:
            # AWS S3 Configuration (using Minio)
            - name: AWS_S3_REGION_NAME
              value: "us-east-1"
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"
            - name: AWS_REGION
              value: "us-east-1"
            - name: AWS_S3_LAMBDA_BUCKET
              value: "tools"
            - name: AWS_S3_CUSTOM_TOOLS_BUCKET
              value: "tools"
            - name: SELF_HOSTED
              value: "true"
            - name: BACKEND_URL
              value: {{ printf "http://%s-apollo:9900" .Release.Name | quote }}
            - name: AWS_S3_FORCE_PATH_STYLE
              value: "true"
            # OpenAI API Key
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: OPENAI_API_KEY
          resources:
            {{- toYaml .Values.mercury.resources | nindent 12 }}
          {{- with .Values.mercury.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.mercury.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "composio.fullname" . }}-mercury
  namespace: {{ include "composio.namespace" . }}
  labels:
    {{- include "composio.labels" . | nindent 4 }}
    app.kubernetes.io/component: mercury
spec:
  type: {{ .Values.mercury.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.mercury.service.port | default 8080 }}
      targetPort: {{ .Values.mercury.service.port | default 8080 }}
      protocol: TCP
  selector:
    {{- include "composio.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mercury
{{- end }}
