{{- if .Values.externalSecrets.postgres.url }}
apiVersion: v1
kind: Secret
metadata:
  name: external-postgres-secret
  namespace: {{ include "composio.namespace" . }}
  labels:
    {{- include "composio.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
type: Opaque
data:
  url: {{ .Values.externalSecrets.postgres.url | b64enc }}
{{- end }} 