# TODO: encryption-key key at 2 places
{{- $secretName := printf "%s-apollo-admin-token" .Release.Name -}}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- if not $secret }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    helm.sh/resource-policy: keep
  name: {{ $secretName }}
type: Opaque
stringData:
  APOLLO_ADMIN_TOKEN: {{ include "apollo-admin-token" . }}
{{- end }}
---
{{- $secretName := printf "%s-composio-api-key" .Release.Name -}}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- if not $secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    helm.sh/resource-policy: keep
stringData:
  COMPOSIO_API_KEY: {{ include "composio-api-key" . }}
{{- end }}
---
{{- $secretName := printf "%s-encryption-key" .Release.Name -}}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- if not $secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  ENCRYPTION_KEY: {{ include "encryption-key" . }}
{{- end }}
---
{{- $secretName := printf "%s-jwt-secret" .Release.Name -}}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- if not $secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  JWT_SECRET: {{ include "jwt-secret" . }}
{{- end }}
---
{{- if .Values.openAI.enabled }}
{{- $secretName := printf "%s-openai-credentials" .Release.Name -}}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- if not $secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  OPENAI_API_KEY: {{ include "getSecretCred" (dict "name" .Values.openAI.secretRef "namespace" .Release.Namespace "key" .Values.openAI.key) }}
{{- end }}
{{- end }}
---
{{- if eq .Values.apollo.objectStorage.backend "s3" }}
{{- $secretName := printf "%s-s3-credentials" .Release.Name -}}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- if not $secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  S3_ACCESS_KEY_ID: {{ include "getSecretCred" (dict "name" $.Values.apollo.objectStorage.accessKey.secretName "namespace" .Release.Namespace "key" $.Values.apollo.objectStorage.accessKey.key) }}
  S3_SECRET_ACCESS_KEY: {{ include "getSecretCred" (dict "name" $.Values.apollo.objectStorage.secretKey.secretName "namespace" .Release.Namespace "key" $.Values.apollo.objectStorage.secretKey.key) }}
{{- end }}
{{- end }}
---
{{- if $.Values.smtp.connectionString }}
{{- $secretName := printf "%s-smtp-credentials" .Release.Name -}}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- if not $secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  SMTP_CONNECTION_STRING: "smtp://{{ .Values.smtp.username }}:{{ include "getSecretCred" (dict "name" .Values.smtp.password.secretRef "namespace" .Release.Namespace "key" .Values.smtp.password.key) }}@{{ .Values.smtp.host }}:{{ .Values.smtp.port }}"
{{- end }}
{{- end }}
---
{{- $secretName := printf "%s-temporal-encryption-key" .Release.Name -}}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- if not $secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  TEMPORAL_TRIGGER_ENCRYPTION_KEY: {{ include "temporal-encryption-key" . }}
{{- end }}
---
{{- if eq .Values.apollo.objectStorage.backend "azure_blob_storage" }}
{{- $secretName := printf "%s-azure-connection-string" .Release.Name -}}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- if not $secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  AZURE_CONNECTION_STRING: {{ include "getSecretCred" (dict "name" $.Values.apollo.objectStorage.azureConnectionString.secretName "namespace" .Release.Namespace "key" $.Values.apollo.objectStorage.azureConnectionString.key) }}
{{- end }}
{{- end }}
---
{{- $secretName := "external-postgres-secret" -}}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- if not $secret }}
{{- $rootDb := $.Values.database -}}
{{- $apolloDb := $rootDb.apollo | default dict -}}
{{- $apolloUser := default $rootDb.user $apolloDb.user -}}
{{- $apolloHost := default $rootDb.host $apolloDb.host -}}
{{- $apolloPort := default $rootDb.port $apolloDb.port -}}
{{- $apolloDatabase := default "" $apolloDb.database -}}
{{- $apolloSslmode := default $rootDb.sslmode $apolloDb.sslmode -}}
{{- $apolloPassword := default $rootDb.password $apolloDb.password -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  password: {{ include "getSecretCred" (dict "name" $apolloPassword.secretRef "namespace" .Release.Namespace "key" $apolloPassword.key) }}
  url: "postgresql://{{ $apolloUser }}:{{ include "getSecretCred" (dict "name" $apolloPassword.secretRef "namespace" .Release.Namespace "key" $apolloPassword.key) }}@{{ $apolloHost }}:{{ $apolloPort }}/{{ $apolloDatabase }}?sslmode={{ $apolloSslmode }}"
{{- end }}
---
{{- $secretName := "external-thermos-postgres-secret" -}}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- if not $secret }}
{{- $thermosDb := $rootDb.thermos | default dict -}}
{{- $thermosUser := default $rootDb.user $thermosDb.user -}}
{{- $thermosHost := default $rootDb.host $thermosDb.host -}}
{{- $thermosPort := default $rootDb.port $thermosDb.port -}}
{{- $thermosDatabase := default "" $thermosDb.database -}}
{{- $thermosSslmode := default $rootDb.sslmode $thermosDb.sslmode -}}
{{- $thermosPassword := default $rootDb.password $thermosDb.password -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  password: {{ include "getSecretCred" (dict "name" $thermosPassword.secretRef "namespace" .Release.Namespace "key" $thermosPassword.key) }}
  url: "postgresql://{{ $thermosUser }}:{{ include "getSecretCred" (dict "name" $thermosPassword.secretRef "namespace" .Release.Namespace "key" $thermosPassword.key) }}@{{ $thermosHost }}:{{ $thermosPort }}/{{ $thermosDatabase }}?sslmode={{ $thermosSslmode }}"
{{- end }}
---
{{- if .Values.externalRedis }}
{{- $secretName := "external-redis-secret" -}}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- if not $secret }}
{{- $password := include "getSecretCred" (dict "name" $.Values.redisConnection.password.secretRef "namespace" .Release.Namespace "key" $.Values.redisConnection.password.key) | trim }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    helm.sh/resource-policy: keep
type: Opaque
stringData:
{{- if $password }}
  url: "redis://:{{ $password }}@{{ .Values.redisConnection.host }}:{{ .Values.redisConnection.port }}/0"
{{- else }}
  url: "redis://{{ .Values.redisConnection.host }}:{{ .Values.redisConnection.port }}/0"
{{- end }}
{{- end }}
{{- end }}
