# TODO: encryption-key key at 2 places
{{- $secretName := printf "%s-apollo-admin-token" .Release.Name -}}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- if not $secret }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    helm.sh/resource-policy: keep
  name: {{ $secretName }}
type: Opaque
stringData:
  APOLLO_ADMIN_TOKEN: {{ include "apollo-admin-token" . }}
{{- end }}
---
{{- $secretName := printf "%s-composio-api-key" .Release.Name -}}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- if not $secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    helm.sh/resource-policy: keep
stringData:
  COMPOSIO_API_KEY: {{ include "composio-api-key" . }}
{{- end }}
---
{{- $secretName := printf "%s-encryption-key" .Release.Name -}}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- if not $secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  ENCRYPTION_KEY: {{ include "encryption-key" . }}
{{- end }}
---
{{- $secretName := printf "%s-jwt-secret" .Release.Name -}}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- if not $secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  JWT_SECRET: {{ include "jwt-secret" . }}
{{- end }}
---
{{- if .Values.openAI.API_KEY }}
{{- $secretName := printf "%s-openai-credentials" .Release.Name -}}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- if not $secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  OPENAI_API_KEY: {{ $.Values.openAI.API_KEY }}
{{- end }}
{{- end }}
---
{{- if .Values.objectStorage.s3.S3_ACCESS_KEY_ID }}
{{- $secretName := printf "%s-s3-credentials" .Release.Name -}}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- if not $secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  S3_ACCESS_KEY_ID: {{ $.Values.objectStorage.s3.S3_ACCESS_KEY_ID }}
  S3_SECRET_ACCESS_KEY: {{ $.Values.objectStorage.s3.S3_SECRET_ACCESS_KEY }}
{{- end }}
{{- end }}
---
{{- if $.Values.smtp.connectionString }} 
{{- $secretName := printf "%s-smtp-credentials" .Release.Name -}}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- if not $secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  SMTP_CONNECTION_STRING: {{ $.Values.smtp.connectionString }}
{{- end }}
{{- end }}
---
{{- $secretName := printf "%s-temporal-encryption-key" .Release.Name -}}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- if not $secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  TEMPORAL_TRIGGER_ENCRYPTION_KEY: {{ include "temporal-encryption-key" . }}
{{- end }}
---
{{- if .Values.objectStorage.azure.connectionString }}
{{- $secretName := printf "%s-azure-connection-string" .Release.Name -}}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- if not $secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  AZURE_CONNECTION_STRING: {{ $.Values.objectStorage.azure.connectionString }}
{{- end }}
{{- end }}
---
############## Database ##############
{{- $secretName := "external-postgres-secret" -}}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- if not $secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  password: {{ include "getSecretCred" (dict
        "name" $.Values.database.apollo.password.secretRef
        "namespace" .Release.Namespace
        "key" $.Values.database.apollo.password.key 
    ) }}
  url: "postgresql://{{ .Values.database.apollo.user }}:{{ include "getSecretCred" (dict
        "name" $.Values.database.apollo.password.secretRef
        "namespace" .Release.Namespace
        "key" $.Values.database.apollo.password.key 
    ) }}@{{ .Values.database.apollo.host }}:{{ .Values.database.apollo.port }}/{{ .Values.database.apollo.database }}?sslmode={{ .Values.database.apollo.sslmode }}"
{{- end }}
---
{{- $secretName := "external-thermos-postgres-secret" -}}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- if not $secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  password: {{ include "getSecretCred" (dict
        "name" $.Values.database.thermos.password.secretRef
        "namespace" .Release.Namespace
        "key" $.Values.database.thermos.password.key 
    ) }}
  url: "postgresql://{{ .Values.database.thermos.user }}:{{ include "getSecretCred" (dict
        "name" $.Values.database.thermos.password.secretRef
        "namespace" .Release.Namespace
        "key" $.Values.database.thermos.password.key 
    ) }}@{{ .Values.database.thermos.host }}:{{ .Values.database.thermos.port }}/{{ .Values.database.thermos.database }}?sslmode={{ .Values.database.thermos.sslmode }}"
{{- end }}
---
{{- $secretName := "external-redis-secret" -}}
{{- if .Values.externalRedis  }}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- if not $secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  url: "redis://{{ .Values.redisConnection.username }}:{{ include "getSecretCred" (dict
        "name" $.Values.redisConnection.password.secretRef
        "namespace" .Release.Namespace
        "key" $.Values.redisConnection.password.key 
    ) }}@{{ .Values.redisConnection.host }}:{{ .Values.redisConnection.port }}"
{{- end }}
{{- end }}
---

