{{- if .Values.supportBundle.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "myapp.fullname" . }}-support-bundle-job
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
    app.kubernetes.io/component: support-bundle
  annotations:
    "helm.sh/hook": manual
    "helm.sh/hook-weight": "5"
spec:
  template:
    metadata:
      labels:
        {{- include "myapp.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: support-bundle
    spec:
      securityContext:
        {{- toYaml .Values.supportBundle.podSecurityContext | nindent 8 }}
      restartPolicy: Never
      serviceAccountName: {{ include "myapp.fullname" . }}-support-bundle
      containers:
      - name: support-bundle
        image: "replicated/troubleshoot:{{ .Values.supportBundle.troubleshootVersion | default "v0.84.0" }}"
        imagePullPolicy: IfNotPresent
        securityContext:
            {{- toYaml .Values.supportBundle.containerSecurityContext | nindent 12 }}
        command:
        - support-bundle
        args:
        - "secret/{{ include "myapp.fullname" . }}-support-bundle"
        - "--output={{ .Values.supportBundle.outputPath | default "/tmp/support-bundle" }}"
        {{- if .Values.supportBundle.interactive }}
        - "--interactive=false"
        {{- end }}
        {{- if .Values.supportBundle.redact }}
        - "--redact=true" 
        {{- end }}
        volumeMounts:
        - name: output
          mountPath: {{ .Values.supportBundle.outputPath | default "/tmp/support-bundle" }}
        env:
        - name: KUBECONFIG
          value: "/tmp/kubeconfig"
        resources:
          limits:
            memory: {{ .Values.supportBundle.resources.limits.memory | default "512Mi" }}
            cpu: {{ .Values.supportBundle.resources.limits.cpu | default "500m" }}
          requests:
            memory: {{ .Values.supportBundle.resources.requests.memory | default "256Mi" }}
            cpu: {{ .Values.supportBundle.resources.requests.cpu | default "100m" }}
      volumes:
      - name: output
        {{- if .Values.supportBundle.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "myapp.fullname" . }}-support-bundle-pvc
        {{- else }}
        emptyDir: {}
        {{- end }}
{{- end }}