{{- if .Values.supportBundle.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "composio.fullname" . }}-support-bundle-instructions
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "composio.labels" . | nindent 4 }}
    app.kubernetes.io/component: support-bundle
data:
  instructions.md: |
    # Support Bundle Instructions
    
    ## Generating a Support Bundle
    
    ### Option 1: Using kubectl (Recommended for air-gapped environments)
    
    ```bash
    # Install the troubleshoot kubectl plugin
    kubectl krew install support-bundle
    
    # Generate support bundle from the secret
    kubectl support-bundle secret/{{ include "composio.fullname" . }}-support-bundle -n {{ .Release.Namespace }}
    ```
    
    ### Option 2: Using the Job (Automated)
    
    ```bash
    # Trigger the support bundle job
    kubectl create job --from=job/{{ include "composio.fullname" . }}-support-bundle-job \
        {{ include "composio.fullname" . }}-support-bundle-manual-$(date +%s) \
        -n {{ .Release.Namespace }}
    
    # Check job status
    kubectl get jobs -n {{ .Release.Namespace }} -l app.kubernetes.io/component=support-bundle
    
    # Get the support bundle from the pod
    kubectl logs job/{{ include "composio.fullname" . }}-support-bundle-manual-xxxxx -n {{ .Release.Namespace }}
    ```
    
    ### Option 3: Direct download (if you have troubleshoot binary)
    
    ```bash
    # Download troubleshoot binary
    curl -L https://github.com/replicatedhq/troubleshoot/releases/latest/download/support-bundle_linux_amd64.tar.gz | tar xzvf -
    
    # Generate support bundle
    ./support-bundle secret/{{ include "composio.fullname" . }}-support-bundle --kubeconfig ~/.kube/config
    ```
    
    ## Sending the Support Bundle
    
    1. The generated support bundle will be a `.tar.gz` file
    2. This file contains redacted logs and cluster information
    3. Email this file to: {{ .Values.supportBundle.supportEmail | default "support@yourcompany.com" }}
    4. Include your ticket number in the subject line
    
    ## What's Included
    
    - Application logs (last 30 days)
    - Kubernetes events
    - Resource definitions (ConfigMaps, Secrets metadata only)
    - Cluster information (nodes, storage, networking)
    - Application-specific diagnostics
    
    ## Data Privacy
    
    - Passwords and sensitive data are automatically redacted
    - Secret values are not included (only metadata)
    - Connection strings are masked
    - Only metadata from your application namespace is collected
    
    ## Troubleshooting
    
    If you encounter issues generating the support bundle:
    
    1. Check RBAC permissions:
       ```bash
       kubectl auth can-i get pods --as=system:serviceaccount:{{ .Release.Namespace }}:{{ include "composio.fullname" . }}-support-bundle
       ```
    
    2. Check if the secret exists:
       ```bash
       kubectl get secret {{ include "composio.fullname" . }}-support-bundle -n {{ .Release.Namespace }}
       ```
    
    3. Manually collect basic information:
       ```bash
       kubectl get pods,services,configmaps -n {{ .Release.Namespace }}
       kubectl logs -l app.kubernetes.io/name={{ include "composio.name" . }} -n {{ .Release.Namespace }} --tail=1000
       ```
{{- end }}