# Development values for Composio
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Namespace configuration
# If create is true, the chart will create namespaces needed by services
# If create is false, you need to create namespaces externally before deploying
namespace:
  create: true
  # Name of the namespace where Composio services will be deployed
  # If not specified, defaults to "composio"
  name: "composio"

global:
  environment: development
  domain: localhost
  imagePullSecrets:
    - name: ecr-secret
  # Add global security defaults for GKE Autopilot

# External secrets configuration
# Pass these during helm install using --set flags:
# --set externalSecrets.ecr.token="$(aws ecr get-login-password --region us-east-1)"
# --set externalSecrets.postgres.url="postgresql://user:pass@host:port/db"
# --set externalSecrets.redis.url="redis://user:pass@host:port"
externalSecrets:
  # ECR authentication
  ecr:
    token: ""
    server: "AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com"
    username: "AWS"
  
  # PostgreSQL configuration  
  postgres:
    url: ""
  
  # Redis configuration
  redis:
    url: ""

# Global secrets configuration for development
# All secrets will be auto-generated for security
secrets:
  openaiApiKey: ""

externalPostgreSQL:
  enabled: true
  urlSecret:
    name: "external-postgres-secret"
    key: "url"

# External Redis configuration
# To use external Redis:
# 1. Set externalRedis.enabled: true
# 2. Set redis.enabled: false
# 3. Provide Redis URL via: --set externalSecrets.redis.url="redis://user:pass@host:port/db"
externalRedis:
  enabled: false
  urlSecret:
    name: "external-redis-secret"
    key: "url"
    
redis:
  # Note: Set enabled to false when using external Redis (externalRedis.enabled: true)
  enabled: true
  auth:
    enabled: true
    password: "redis123"
  architecture: standalone
  master:
    persistence:
      enabled: true
      size: 8Gi
    resources:
      requests:
        memory: "4Gi"
        cpu: "2"
      limits:
        memory: "4Gi"
        cpu: "2"
    # Disable privileged sysctls for GKE Autopilot
    sysctlImage:
      enabled: false
    sysctl:
      enabled: false


# Apollo service configuration - Development
apollo:
  replicaCount: 2
  image:
    repository: AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/composio-self-host/apollo
    tag: "1.0-20250717-d3eccab"
    pullPolicy: Always
  
  service:
    type: NodePort
    port: 9900
    nodePort: 30900
  
  resources:
    requests:
      memory: "4Gi"
      cpu: "2"
    limits:
      memory: "4Gi"
      cpu: "2"
  
  database:
    urlSecret:
      name: "external-postgres-secret"
      key: "url"
  
  # Note: Secrets are now managed globally in the 'secrets' section

# MCP service configuration - Development
mcp:
  replicaCount: 2
  image:
    repository: AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/composio-self-host/mcp-server
    tag: "1.0-20250717-d3eccab"
    pullPolicy: Always
  
  service:
    type: ClusterIP
    port: 3000
  
  resources:
    requests:
      memory: "4Gi"
      cpu: "2"
    limits:
      memory: "4Gi"
      cpu: "2"
  
  database:
    urlSecret:
      name: "external-postgres-secret"
      key: "url"
  
  # Note: Secrets are now managed globally in the 'secrets' section

# Thermos service configuration - Development
thermos:
  replicaCount: 2
  image:
    repository: AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/composio-self-host/thermos
    tag: "1.0-20250717-d3eccab"
    pullPolicy: Always
  
  service:
    type: ClusterIP
    port: 8180
  
  resources:
    requests:
      memory: "4Gi"
      cpu: "2"
    limits:
      memory: "4Gi"
      cpu: "2"
  
  # Note: Secrets are now managed globally in the 'secrets' section

# DB Init - Enabled for development
dbInit:
  image:
    repository: AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/composio-self-host/init
    tag: "1.0-20250717-d3eccab"
    pullPolicy: Always
  adminEmail: "hello@composio.dev"
  database:
    urlSecret:
      name: "external-postgres-secret"
      key: "url"

# Temporal configuration - Using official helm chart as dependency with external PostgreSQL
temporal:
  fullnameOverride: "temporal-stack"
  
  server:
    enabled: true
    replicaCount: 2
    
    config:
      logLevel: "info"
      numHistoryShards: 512
      
      # Configure persistence to use PostgreSQL from external secret
      persistence:
        defaultStore: default
        
        # Main temporal database  
        default:
          driver: "sql"
          sql:
            driver: "postgres12"
            host: ""
            port: 5432
            database: "temporal"
            user: "postgres"
            existingSecret: "external-postgres-secret"
            maxConns: 20
            maxIdleConns: 20
            maxConnLifetime: "1h"
        
        # Visibility database (will be created by schema setup)
        visibility:
          driver: "sql" 
          sql:
            driver: "postgres12"
            host: ""
            port: 5432
            database: "temporal_visibility"
            user: "postgres"
            existingSecret: "external-postgres-secret"
            maxConns: 20
            maxIdleConns: 20
            maxConnLifetime: "1h"

    # Frontend service configuration
    frontend:
      service:
        type: ClusterIP
        port: 7233
        membershipPort: 6933
        httpPort: 7243

  # Enable schema setup to create temporal databases
  schema:
    createDatabase:
      enabled: true
    setup:
      enabled: true
      backoffLimit: 100
    update:
      enabled: true
      backoffLimit: 100

  # Enable web UI
  web:
    enabled: true
    replicaCount: 1
    service:
      type: ClusterIP
      port: 8080
  
  admintools:
    enabled: true

  cassandra:
    enabled: false
  mysql:
    enabled: false
  elasticsearch:
    enabled: false
    
  prometheus:
    enabled: false
    nodeExporter:
      enabled: false
  grafana:
    enabled: false

prometheus:
  enabled: false
  nodeExporter:
    enabled: false
  imagePullSecrets: []

grafana:
  enabled: false
  replicas: 1

testFramework:
  enabled: false

rbac:
  create: false
  pspEnabled: false
  namespaced: true

elasticsearch:
  enabled: false

cassandra:
  enabled: false

ingress:
  enabled: false

serviceAccount:
  create: true
  annotations: {}
  name: ""

nodeSelector: {}

tolerations: []

affinity: {}

# AWS configuration - disabled for development
aws:
  region: us-east-1
  s3:
    lambdaBucketName: "tools"
  lambda:
    functionName: "mercury"
    
# Minio configuration - Development
minio:
  replicaCount: 1
  image:
    repository: AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/composio-self-host/minio
    tag: "latest"
    pullPolicy: Always
  
  service:
    type: ClusterIP
  
  auth:
    rootUser: "minioadmin"
    rootPassword: "minioadmin123"
  
  persistence:
    enabled: true
    size: 8Gi
    accessMode: ReadWriteOnce
    storageClass: ""
  
  resources:
    requests:
      memory: "4Gi"
      cpu: "2"
    limits:
      memory: "4Gi"
      cpu: "2"
  
  livenessProbe:
    httpGet:
      path: /minio/health/live
      port: 9000
    initialDelaySeconds: 120
    periodSeconds: 30
  
  readinessProbe:
    httpGet:
      path: /minio/health/ready
      port: 9000
    initialDelaySeconds: 30
    periodSeconds: 10
  
  extraEnvVars: []

# Mercury service configuration - Development
mercury:
  enabled: true
  useKnative: true
  replicaCount: 1
  image:
    repository: AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/composio-self-host/mercury
    tag: "latest"
    pullPolicy: Always
  
  # Let the container use its default entrypoint
  # command: []
  # args: []
  
  service:
    type: ClusterIP
    port: 8080
  
  autoscaling:
    minScale: 1
    maxScale: 10
    target: 80
  
  containerConcurrency: 0
  timeoutSeconds: 300
  
  resources:
    requests:
      memory: "8Gi"
      cpu: "4"
    limits:
      memory: "16Gi"
      cpu: "8"
      
  knative:
    minReplicas: 1
    replicas: 2
    maxReplicas: 5

  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 1000
    capabilities:
      drop:
      - ALL
    seccompProfile:
      type: RuntimeDefault
  
  ingress:
    enabled: false
    className: ""
    annotations: {}
    host: ""
    tls: []
  
  volumeMounts: []
  volumes: []
  

